#!/bin/bash

### Grupo: SO-TI-04
# Aluno 1: Libero Suprani (fc62220)
# Aluno 2: Ravi Mughal (fc62504)
# Aluno 3: Ricardo Avelãs (fc62257)

PYTHON="python3" 
PROGRAM="pword.py" 

# constants
readonly DEFAULT_MODE="c"
readonly DEFAULT_PARALLELIZATION=1
readonly DEFAULT_INTERVAL=3
readonly DEFAULT_LOGFILE="stdout"
readonly VALID_MODES=("c" "l" "i")
# readonly OPTIONS=":hm:p:w:i:d:"
readonly OPTIONS=":hm:p:i:d:w:"

# initializing variables with their default value
mode=$DEFAULT_MODE
parallelization=$DEFAULT_PARALLELIZATION
interval=$DEFAULT_INTERVAL
logfile=$DEFAULT_LOGFILE
word=0

# checks whether the value given in -m is one of the valid modes
validate_mode() {
    for m in "${VALID_MODES[@]}"; do
        if [ "$1" == "$m" ]; then
            return 0
        fi
    done
    return 1
}

# checks whether the value given in -p is a positive integer number
validate_positive_integer() {
    if [[ "$1" =~ ^[0-9]+$ && "$1" -gt 0 ]]; then
        return 0
    else
        return 1
    fi
}

while getopts $OPTIONS option; do
    case $option in
        h)
            printf "pword -m [c|l|i] [-p n] [-i s] [-d f] -w palavra {ficheiros}\nDefault: [-m c] [-p 1] [-i 3] [-d stdout]\n"
            exit 1
            ;;
        m)
            mode=$OPTARG
            validate_mode "$mode"
            is_valid=$?
            if [ $is_valid -eq 1 ]; then
                echo "Argumento inválido. (-$option $mode)"
                exit 1 
            fi
            ;;
        p)
            parallelization=$OPTARG
            validate_positive_integer "$parallelization"
            is_valid=$?
            if [ $is_valid -eq 1 ]; then
                echo "Argumento inválido. (-${option} ${parallelization})"
                exit 1
            fi
            ;;
        i)
            interval=$OPTARG
            validate_positive_integer "$interval"
            is_valid=$?
            if [ $is_valid -eq 1 ]; then
                echo "Argumento inválido. (-${option} ${interval})"
                exit 1
            fi
            ;;
        d)
            logfile=$OPTARG
            ;;
        w)
            word=$OPTARG
            ;;
        :)
            echo "Opção -${OPTARG} passada sem argumentos."
            exit 1
            ;;
        ?)
            echo "Opção inválida: -${OPTARG}."
            exit 1
            ;;
    esac
done

# points to the last argument given through the command line
# in this case, the file or files
shift $((OPTIND - 1))

files=("$@")

# no word was given
if [ "$word" == 0 ]; then
    echo "Opção -w é obrigatória."
    exit 1
fi

# number of files less than 1 (no files were given)
if [ ${#files} -lt 1 ]; then
    echo "Deve ser passado o nome de pelo menos 1 ficheiro."
    exit 1
fi

if test -a ${PROGRAM}; then
    args=("$mode" "$parallelization" "$interval" "$logfile" "$word" "${files[@]}")
    ${PYTHON} ${PROGRAM} "${args[@]}"
else
    echo "O ficheiro ${PROGRAM} não existe ou não pôde ser encontrado."
    exit 1
fi
